routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register Admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "admin" middleware group. Enjoy building your Dashboard!
|
*/

Route::redirect('/', '/admin/categories')->name('dashboard');
//Route::get('/', 'DashboardController@index')->name('dashboard');

Route::resource('categories', 'CategoryController')->except(['show']);
Route::resource('slider', 'SliderController')->except(['show']);
Route::resource('products', 'ProductController')->except(['show']);

routes/web.php
<?php

use Adldap\Laravel\Facades\Adldap;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('users', function() {
    $users = Adldap::search()->users()->find('jbokuchava');

    return $users;
});

Route::get('/', 'HomeController@index')->name('home');
Route::view('/rules', 'rules')->name('rules');
Route::view('/partnership', 'partnership')->name('partnership');

// Login
Route::post('login', 'Auth\LoginController@login')->name('login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

/**
 * /category/{slug}?filter={BASE64_FILTER}
 *
 * {
 *   "categories": [1, 6],
 *   "brands": [3, 8],
 *   "rating": 3.5
 * }
 */
Route::get('/category/{category}', 'CategoryController@show')->name('category');

/**
 * /products?filter={BASE64_FILTER}
 *
 * {
 *   "query": 'სმოკინგი',
 *   "categories": [1, 6],
 *   "brands": [3, 8],
 *   "rating": 3.5
 * }
 */
Route::get('/products', 'ProductController@index')->name('products');

// /product/{id}
Route::get('/product/{product}', 'ProductController@show')->name('product');

// /cart?page=current | /cart?page=history
Route::get('/cart', 'CartController@index')->name('cart');

// /page/{slug}
//Route::get('/page/{page}', 'PageController@show')->name('page');

// /payment
Route::get('/payment/check', 'PaymentController@check')->name('payment.check');
Route::get('/payment/init', 'PaymentController@init')->name('payment.init');

resources/views/admin/layouts/partials/_footer.blade.php
<footer class="c-footer c-footer--small">
    <div class="o-wrapper u-text--center">
        <span class="u-text--muted">შექმნილია 💛️-ით "საქართველოს ბანკი"-სთვის</span>
    </div>
    <!-- /.o-wrapper -->
</footer>
<!-- /.c-footer -->

resources/views/admin/layouts/partials/_header.blade.php
<header class="c-header">
    <div class="o-wrapper">
        <a href="{{ url('/') }}" class="c-logo">Dashboard</a>

        <div class="c-header__controls">
            <button class="o-button c-button u-text--uppercase">გასვლა</button>
        </div>
        <!-- /.c-header__controls -->
    </div>
    <!-- /.o-wrapper -->
</header>
<!-- /.c-header -->

resources/views/admin/layouts/partials/_navigation.blade.php
<nav class="c-navigation">
    <div class="o-wrapper">
        <ul class="c-navigation__list">
            <li class="c-navigation__item">
                <a class="c-navigation__link u-text--uppercase {{ request()->is('admin/categories*') ? 'is-active' : '' }}" href="{{ route('categories.index') }}">
                    კატეგორიები
                </a>
                <!-- /.nav-link -->
            </li>
            <!-- /.c-navigation__item -->

            <li class="c-navigation__item">
                <a class="c-navigation__link u-text--uppercase {{ request()->is('admin/slider*') ? 'is-active' : '' }}" href="{{ route('slider.index') }}">
                    სლაიდერი
                </a>
                <!-- /.nav-link -->
            </li>
            <!-- /.c-navigation__item -->

            <li class="c-navigation__item">
                <a class="c-navigation__link u-text--uppercase {{ request()->is('admin/products*') ? 'is-active' : '' }}" href="{{ route('products.index') }}">
                    პროდუქცია
                </a>
                <!-- /.nav-link -->
            </li>
            <!-- /.c-navigation__item -->

            <li class="c-navigation__item">
                <a class="c-navigation__link u-text--uppercase {{ request()->is('admin/transactions*') ? 'is-active' : '' }}" href="#">
                    ტრანზაქციები
                </a>
                <!-- /.nav-link -->
            </li>
            <!-- /.c-navigation__item -->

            <li class="c-navigation__item">
                <a class="c-navigation__link u-text--uppercase {{ request()->is('admin/purchases*') ? 'is-active' : '' }}" href="#">
                    შეკვეთები
                </a>
                <!-- /.nav-link -->
            </li>
            <!-- /.c-navigation__item -->
        </ul>
        <!-- /.c-navigation__list -->
    </div>
    <!-- /.o-wrapper -->
</nav>
<!-- /.c-navigation -->

resources/views/admin/layouts/partials/_sidebar.blade.php
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
    <div class="sidebar-sticky">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link {{ request()->is('admin') ? 'active' : '' }}" href="{{ route('dashboard') }}">
                    <i class="c-icon c-icon--home"></i>
                    სამართავი პანელი
                </a>
                <!-- /.nav-link -->
            </li>
            <!-- /.nav-item -->

            <li class="nav-item">
                <a class="nav-link {{ request()->is('admin/categories') ? 'active' : '' }}" href="{{ route('categories') }}">
                    <i class="c-icon c-icon--folder"></i>
                    კატეგორიები
                </a>
                <!-- /.nav-link -->
            </li>
            <!-- /.nav-item -->

            <li class="nav-item">
                <a class="nav-link {{ request()->is('admin/brands') ? 'active' : '' }}" href="#">
                    <i class="c-icon c-icon--award"></i>
                    ბრენდები
                </a>
                <!-- /.nav-link -->
            </li>
            <!-- /.nav-item -->

            <li class="nav-item">
                <a class="nav-link {{ request()->is('admin/slider') ? 'active' : '' }}" href="#">
                    <i class="c-icon c-icon--film"></i>
                    სლაიდერი
                </a>
                <!-- /.nav-link -->
            </li>
            <!-- /.nav-item -->
        </ul>
        <!-- /.nav -->

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>პროდუქცია</span>
        </h6>
        <!-- /.sidebar-heading -->

        <ul class="nav flex-column mb-2">
            <li class="nav-item">
                <a class="nav-link {{ request()->is('admin/featured') ? 'active' : '' }}" href="#">
                    <i class="c-icon c-icon--star"></i>
                    გამორჩეული პროდუქცია
                </a>
                <!-- /.nav-link -->
            </li>
            <!-- /.nav-item -->

            <li class="nav-item">
                <a class="nav-link {{ request()->is('admin/products') ? 'active' : '' }}" href="#">
                    <i class="c-icon c-icon--package"></i>
                    პროდუქციის მართვა
                </a>
                <!-- /.nav-link -->
            </li>
            <!-- /.nav-item -->
        </ul>
        <!-- /.nav -->

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>ფინანსური ოპერაციები</span>
        </h6>
        <!-- /.sidebar-heading -->

        <ul class="nav flex-column mb-2">
            <li class="nav-item">
                <a class="nav-link {{ request()->is('admin/transactions') ? 'active' : '' }}" href="#">
                    <i class="c-icon c-icon--credit-card"></i>
                    ტრანზაქციები
                </a>
                <!-- /.nav-link -->
            </li>
            <!-- /.nav-item -->

            <li class="nav-item">
                <a class="nav-link {{ request()->is('admin/products') ? 'active' : '' }}" href="#">
                    <i class="c-icon c-icon--shopping-bag"></i>
                    შეკვეთები
                </a>
                <!-- /.nav-link -->
            </li>
            <!-- /.nav-item -->
        </ul>
        <!-- /.nav -->
    </div>
    <!-- /.sidebar-sticky -->
</nav>
<!-- /.sidebar -->