routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register Admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "admin" middleware group. Enjoy building your Dashboard!
|
*/

Route::redirect('/', '/admin/categories')->name('dashboard');
//Route::get('/', 'DashboardController@index')->name('dashboard');

Route::resource('categories', 'CategoryController')->except(['show']);
Route::resource('slider', 'SliderController')->except(['show']);
Route::resource('products', 'ProductController')->except(['show']);

routes/web.php
<?php

use Adldap\Laravel\Facades\Adldap;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('users', function() {
    $users = Adldap::search()->users()->find('jbokuchava');

    return $users;
});

Route::get('/', 'HomeController@index')->name('home');
Route::view('/rules', 'rules')->name('rules');
Route::view('/partnership', 'partnership')->name('partnership');

// Login
Route::post('login', 'Auth\LoginController@login')->name('login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

/**
 * /category/{slug}?filter={BASE64_FILTER}
 *
 * {
 *   "categories": [1, 6],
 *   "brands": [3, 8],
 *   "rating": 3.5
 * }
 */
Route::get('/category/{category}', 'CategoryController@show')->name('category');

/**
 * /products?filter={BASE64_FILTER}
 *
 * {
 *   "query": 'სმოკინგი',
 *   "categories": [1, 6],
 *   "brands": [3, 8],
 *   "rating": 3.5
 * }
 */
Route::get('/products', 'ProductController@index')->name('products');

// /product/{id}
Route::get('/product/{product}', 'ProductController@show')->name('product');

// /cart?page=current | /cart?page=history
Route::get('/cart', 'CartController@index')->name('cart');

// /page/{slug}
//Route::get('/page/{page}', 'PageController@show')->name('page');

// /payment
Route::get('/payment/check', 'PaymentController@check')->name('payment.check');
Route::get('/payment/init', 'PaymentController@init')->name('payment.init');

app/Slider.php
<?php

namespace App;

use File;
use Image;
use Illuminate\Http\Request;
use Intervention\Image\Constraint;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;

class Slider extends Model
{
    const IMAGE_WIDTH = 1300;
    const IMAGE_HEIGHT = 558;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['image', 'link', 'priority'];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = ['image_path'];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'priority' => 'integer',
    ];

    /**
     * @return string
     */
    public function getImagePathAttribute()
    {
        if (!$this->hasImage()) {
            return null;
        }

        return "/storage/slides/{$this->image}.png";
    }

    /**
     * @param Builder $builder
     * @return Builder
     */
    public function scopeByPriority(Builder $builder)
    {
        return $builder->orderBy('priority');
    }

    /**
     * @return bool
     */
    public function hasLink()
    {
        return $this->link !== null;
    }

    /**
     * @return bool
     */
    public function hasImage()
    {
        return $this->image !== null;
    }

    /**
     * @param Request $request
     */
    public function uploadImage(Request $request)
    {
        if (!$request->has('image')) {
            return;
        }

        $hash = hash('sha256', $request->file('image') . time());
        $image = Image::make($request->file('image'));

        $image->fit(static::IMAGE_WIDTH, static::IMAGE_HEIGHT, function (Constraint $constraint) {
            $constraint->upsize();
        });

        $image->save("storage/slides/{$hash}.png");

        $this->image = $hash;
    }

    /**
     * @return static
     */
    public function deleteImage()
    {
        $image = public_path("storage/slides/{$this->image}.png");

        File::delete($image);

        return $this;
    }
}

app/Http/Controllers/API/SliderController.php
<?php

namespace App\Http\Controllers\API;

use App\Slider;
use App\Http\Controllers\Controller;
use App\Http\Resources\SlideResource;

class SliderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Resources\Json\AnonymousResourceCollection
     */
    public function index()
    {
        return SlideResource::collection(
            Slider::byPriority()->latest()->get()
        );
    }
}

app/Http/Controllers/Admin/SliderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Slider;
use App\Http\Controllers\Controller;
use App\Http\Requests\CreateSliderRequest;
use App\Http\Requests\UpdateSliderRequest;

class SliderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $slider = Slider::byPriority()->latest()->paginate(10);

        return view('admin.slider.index', compact('slider'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $slider = new Slider;

        return view('admin.slider.create', compact('slider'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CreateSliderRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateSliderRequest $request)
    {
        $slider = new Slider;
        $slider->link = $request->link;
        $slider->priority = $request->priority;

        $slider->uploadImage($request);

        if ($slider->save()) {
            session()->flash('success', 'სლაიდი დაემატა');
        } else {
            session()->flash('success', 'სლაიდი ვერ დაემატა');
        }

        return redirect()->route('slider.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Slider $slider
     * @return \Illuminate\Http\Response
     */
    public function edit(Slider $slider)
    {
        return view('admin.slider.edit', compact('slider'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateSliderRequest $request
     * @param  \App\Slider $slider
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateSliderRequest $request, Slider $slider)
    {
        $slider->link = $request->link;
        $slider->priority = $request->priority;

        if ($request->has('image')) {
            $slider->uploadImage($request);
        }

        if ($slider->save()) {
            session()->flash('success', 'სლაიდი შეიცვალა');
        } else {
            session()->flash('success', 'სლაიდი ვერ შეიცვალა');
        }

        return redirect()->route('slider.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Slider $slider
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Slider $slider)
    {
        if ($slider->deleteImage()->delete()) {
            session()->flash('success', 'სლაიდი წაიშალა');
        } else {
            session()->flash('success', 'სლაიდი ვერ წაიშალა');
        }

        return back();
    }
}

app/Http/Controllers/SliderController.php
<?php

namespace App\Http\Controllers;

use App\Slider;
use Illuminate\Http\Request;

class SliderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Slider  $slider
     * @return \Illuminate\Http\Response
     */
    public function show(Slider $slider)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Slider  $slider
     * @return \Illuminate\Http\Response
     */
    public function edit(Slider $slider)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Slider  $slider
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Slider $slider)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Slider  $slider
     * @return \Illuminate\Http\Response
     */
    public function destroy(Slider $slider)
    {
        //
    }
}

resources/views/admin/slider/create.blade.php
@extends('admin.layouts.master')

@section('content')
    <div class="o-wrapper u-py-2">
        <div class="u-pb-2">
            <a href="{{ route('slider.index') }}" class="o-button c-button u-text--uppercase">უკან</a>
        </div>
        <!-- /.u-text--center -->

        <fieldset class="c-form">
            <legend class="c-form__legend u-text--uppercase">სლაიდის დამატება</legend>

            <form action="{{ route('slider.store') }}" class="c-form__content" method="post" enctype="multipart/form-data">
                @csrf

                @include('admin.slider.form')
            </form>
        </fieldset>
    </div>
    <!-- /.o-wrapper -->
@endsection

resources/views/admin/slider/edit.blade.php
@extends('admin.layouts.master')

@section('content')
    <div class="o-wrapper u-py-2">
        <div class="u-pb-2">
            <a href="{{ route('slider.index') }}" class="o-button c-button u-text--uppercase">უკან</a>
        </div>
        <!-- /.u-text--center -->

        <fieldset class="c-form">
            <legend class="c-form__legend u-text--uppercase">სლაიდის რედაქტირება</legend>

            <form action="{{ route('slider.update', $slider) }}" class="c-form__content" method="post"
                  enctype="multipart/form-data">
                @csrf
                @method('PUT')

                @include('admin.slider.form')
            </form>
        </fieldset>
    </div>
    <!-- /.o-wrapper -->
@endsection

resources/views/admin/slider/form.blade.php
<div class="c-form__row {{ $errors->has('image') ? 'has-error' : '' }}">
    <label for="image" class="c-form__label">სურათი:</label>
    <input type="file" name="image" id="image" class="c-form__control o-input c-input o-input--file" accept="image/*" @change="fileSelected">
    <label for="image" class="c-file__chooser">აირჩიეთ სურათი...</label>

    @if($errors->has('image'))
        <span class="c-form__message">{{ $errors->first('image') }}</span>
    @endif
</div>
<!-- /.form__row -->

<div class="c-form__row {{ $errors->has('link') ? 'has-error' : '' }}">
    <label for="link" class="c-form__label">მისამართი (URL):</label>
    <input type="url" name="link" id="link" class="c-form__control o-input c-input" value="{{ $slider->link }}">

    @if($errors->has('link'))
        <span class="c-form__message">{{ $errors->first('link') }}</span>
    @endif
</div>
<!-- /.form__row -->

<div class="c-form__row {{ $errors->has('priority') ? 'has-error' : '' }}">
    <label for="priority" class="c-form__label">პრიორიტეტი:</label>
    <input type="number" name="priority" id="priority" class="c-form__control o-input c-input" min="1" value="{{ old('priority', $slider->priority ?? 1) }}">

    @if($errors->has('priority'))
        <span class="c-form__message">{{ $errors->first('priority') }}</span>
    @endif
</div>
<!-- /.form__row -->

<div class="c-form__row c-form__row--unlabeled">
    <button type="submit" class="o-button c-button c-button--success c-button--filled u-text--uppercase">შენახვა</button>
</div>
<!-- /.form__row -->

resources/views/admin/slider/index.blade.php
@extends('admin.layouts.master')

@section('content')
    <div class="o-wrapper u-py-2">
        <div class="u-text--center u-pb-2">
            <a href="{{ route('slider.create') }}" class="o-button c-button c-button--primary u-text--uppercase">
                სლაიდის დამატება
            </a>
            <!-- /.c-button -->
        </div>
        <!-- /.u-text--center -->

        <div class="c-table__wrapper">
            <table class="c-table">
                <thead>
                    <tr>
                        <th>სურათი</th>
                        <th>მისამართი (URL)</th>
                        <th><i class="c-icon c-icon--arrow-down"></i></th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>

                <tbody>
                    @forelse($slider as $slide)
                        <tr class="c-table__row">
                            <td class="u-text--center">
                                @if($slide->hasImage())
                                    <img src="{{ $slide->image_path }}" alt="Slide #{{ $slide->id }}" class="js-zoom" height="100">
                                @endif
                            </td>
                            <td>
                                @if($slide->hasLink())
                                    <a href="{{ $slide->link }}" target="_blank">{{ $slide->link}}</a>
                                @endif
                            </td>
                            <td class="u-text--center">{{ $slide->priority }}</td>
                            <td class="c-table__controls u-text--center">
                                <a href="{{ route('slider.edit', $slide) }}" class="o-button o-button--icon c-button">
                                    <i class="c-icon c-icon--edit"></i>
                                </a>
                                <!-- /.c-button -->

                                <a href="#" @click.prevent="confirmDelete('{{ route('slider.destroy', $slide) }}')"
                                   class="o-button o-button--icon c-button c-button--danger">
                                    <i class="c-icon c-icon--trash"></i>
                                </a>
                                <!-- /.c-button -->
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="4" class="u-text--center">სლაიდერი არ არის დამატებული</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
            <!-- /.c-table -->
        </div>
        <!-- /.c-table__wrapper -->

        {{ $slider->links() }}
    </div>
    <!-- /.o-wrapper -->
@endsection